In [1]:
#INSTALAR LIBRERIAS
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install openpyxl

Requirement already satisfied: pandas in c:\users\dorop\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dorop\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dorop\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dorop\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dorop\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dorop\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in c:\users\dorop\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: matplotlib in c:\users\dorop\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\dorop\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in c:\users\dorop\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\dorop\anaconda3\lib\site-packages (from seaborn) (2.1.3)
Requirement already satisfied: pandas>=1.2 in c:\users\dorop\anaconda3\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\dorop\anaconda3\lib\site-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dorop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dorop\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dorop\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dorop\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: openpyxl in c:\users\dorop\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\dorop\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [2]:
#Importamos librer√≠as requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Convertimos el dataset en dataframe
df= pd.read_csv("listings.csv")
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,538175,https://www.airbnb.com/rooms/538175,20250619031327,2025-06-19,city scrape,Loft with garden on Naviglio Grande,gorgeous loft with garden. Very quiet and comf...,"Neighborhood made by artists, designers, pubs,...",https://a0.muscache.com/pictures/6527563/6060f...,2643876,...,4.56,4.25,4.22,IT015146C2XCMAQN43,f,1,1,0,0,0.06
1,541221,https://www.airbnb.com/rooms/541221,20250619031327,2025-06-19,city scrape,2 rooms apartment in downtown Milan,NaN,The apartment is close to Ticinese going out a...,https://a0.muscache.com/pictures/7108899/66d9b...,1442498,...,4.64,4.50,3.93,IT015146C2GRLPV2TY,f,1,1,0,0,0.13
2,541668,https://www.airbnb.com/rooms/541668,20250619031327,2025-06-19,city scrape,Two-rooms Apartment | 50 meters from Metro,Two-room apartment 50 meters away from the Yel...,"Located on the south-eastern of Milan, the Bre...",https://a0.muscache.com/pictures/miso/Hosting-...,2022842,...,4.94,4.64,4.94,IT015146C2W99LAEKO,f,1,1,0,0,0.41
3,544809,https://www.airbnb.com/rooms/544809,20250619031327,2025-06-19,city scrape,2 km DUOMO wifi aircon PortaRomana,perfect for STUDENTS and YOUNG TURISTS 10 mins...,"extremily reserved, not intrusive. all the apt...",https://a0.muscache.com/pictures/11551732/7b0b...,2452841,...,4.67,4.71,4.42,IT015146C22ZO8W2CJ,f,3,3,0,0,0.93
4,553285,https://www.airbnb.com/rooms/553285,20250619031327,2025-06-19,city scrape,Milano Central Luxury - 3 BDR / 7 Guests,"A stylish and cozy apartment, beautifully furn...","The Central Luxury apartment, is located just ...",https://a0.muscache.com/pictures/miso/Hosting-...,2718914,...,4.89,4.76,4.71,IT015146B4CCMWJAB7,t,27,27,0,0,0.91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22535,1444043842204694335,https://www.airbnb.com/rooms/1444043842204694335,20250619031327,2025-06-19,city scrape,Tranquillo bilocale zona Bicocca vicino alla m...,Stay in Milan in a quiet area but well connect...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,701379726,...,NaN,NaN,NaN,IT015146C2RY62JBIW,f,1,1,0,0,NaN
22536,1444134511111522063,https://www.airbnb.com/rooms/1444134511111522063,20250619031327,2025-06-19,city scrape,Camera matrimoniale con bagno,Double room with a private bathroom with a sho...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,2574070,...,NaN,NaN,NaN,IT015146A1XC7SOVT5,t,3,0,3,0,NaN
22537,1444209901012550835,https://www.airbnb.com/rooms/1444209901012550835,20250619031327,2025-06-19,city scrape,Ingegnoli1 Bright top floor apartment,Located on the third and last floor (there is ...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,303593576,...,NaN,NaN,NaN,IT015146C2GYSOQIWZ,t,10,10,0,0,NaN
22538,1444251694855590556,https://www.airbnb.com/rooms/1444251694855590556,20250619031327,2025-06-19,city scrape,Concetta‚Äôs Urban Nest,NaN,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,701442028,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
22539,1444265456512525732,https://www.airbnb.com/rooms/1444265456512525732,20250619031327,2025-06-19,city scrape,"Bilocale Elegante, Silenzioso, Box, Staz. Cent...","Brand new and well-kept two-room apartment, su...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1761388,...,NaN,NaN,NaN,IT015146C2HVFJUX6K,f,1,1,0,0,NaN

In [4]:
# Acceder a m√°s de una Columna (Array 2D)
columnas1 = df[['host_name', 'host_since','host_neighbourhood', 'property_type', 'room_type','price']] #pueden ser consecutivas o no consecutivas
columnas1

,host_name,host_since,host_neighbourhood,property_type,room_type,price
0,Barbara,2012-06-15,NaN,Entire loft,Entire home/apt,$100.00
1,Elena,2011-11-25,NaN,Entire rental unit,Entire home/apt,$110.00
2,Matteo,2012-03-28,Zona 4,Entire condo,Entire home/apt,$42.00
3,Paolo & Yuki,2012-05-24,Porta Romana,Entire rental unit,Entire home/apt,$73.00
4,Nicola,2012-06-23,Centro Direzionale,Entire rental unit,Entire home/apt,$371.00
...,...,...,...,...,...,...
22535,Luciano,2025-06-15,NaN,Entire rental unit,Entire home/apt,$55.00
22536,Enrico,2012-06-07,NaN,Room in hotel,Private room,$90.00
22537,Davide,2019-10-21,NaN,Entire rental unit,Entire home/apt,$80.00
22538,Concetta,2025-06-15,NaN,Entire rental unit,Entire home/apt,$87.00
22539,Massimo Claudio,2012-02-16,NaN,Entire rental unit,Entire home/apt,$115.00

In [5]:
df3= df.iloc[ [1] + [50] + list(range(100, 201)) + [499] + [500] + [605] + [1500] + [8000] + [15000] , : ] 
df3

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
1,541221,https://www.airbnb.com/rooms/541221,20250619031327,2025-06-19,city scrape,2 rooms apartment in downtown Milan,NaN,The apartment is close to Ticinese going out a...,https://a0.muscache.com/pictures/7108899/66d9b...,1442498,...,4.64,4.50,3.93,IT015146C2GRLPV2TY,f,1,1,0,0,0.13
50,710637,https://www.airbnb.com/rooms/710637,20250619031327,2025-06-19,previous scrape,"STUDIO CLOSE TO BOCCONI University, NABA, IULM",Very quite and lovely studio.Kitchenette with ...,NaN,https://a0.muscache.com/pictures/9576252/25ad8...,2158679,...,5.00,4.75,5.00,NaN,f,5,5,0,0,0.03
100,806673,https://www.airbnb.com/rooms/806673,20250619031327,2025-06-19,city scrape,At Isola district as at home,Comfortable apartment of 62 square meters for ...,The apartment is located on the border between...,https://a0.muscache.com/pictures/60345526/6c1e...,4246019,...,4.92,4.85,4.82,IT015146C2URY7KWZT,f,1,1,0,0,2.31
101,810216,https://www.airbnb.com/rooms/810216,20250619031327,2025-06-19,city scrape,‚Ä¢‚Ä¢Luxury Bohemian loft NAVIGLI area 6persons‚Ä¢‚Ä¢,"prestigious loft, extremely bright located ins...","navigli area, considered the most characterist...",https://a0.muscache.com/pictures/18532366/02dd...,4236040,...,4.72,4.67,4.59,IT015146C238LKT99Z,f,2,2,0,0,0.41
102,812419,https://www.airbnb.com/rooms/812419,20250619031327,2025-06-19,previous scrape,Quiet & central one bedroom apartment,"Quiet and central apartment, 70 sqm. Walking d...","Boutiques, restaurants, cafes and pastry shops...",https://a0.muscache.com/pictures/24086509-8432...,3052996,...,4.99,4.99,4.91,IT015146B4QN9XQ659,f,1,1,0,0,0.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,3327251,https://www.airbnb.com/rooms/3327251,20250619031327,2025-06-19,city scrape,Room with a view near the centre,We're a family and live in a newly renovated L...,The house is located in the district of Citt√† ...,https://a0.muscache.com/pictures/miso/Hosting-...,1875788,...,4.86,4.73,4.87,IT015146C2ZDTIUOJV,f,2,0,2,0,0.12
605,5020692,https://www.airbnb.com/rooms/5020692,20250619031327,2025-06-19,city scrape,Centro/Navigli affitto per Expo2015,Weekly rental period Expo 2015 apartment in d...,NaN,https://a0.muscache.com/pictures/62858623/8ee8...,25903276,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN
1500,11580800,https://www.airbnb.com/rooms/11580800,20250619031327,2025-06-19,previous scrape,"Brand New Flat, City Life District 15 min - D...",This brand new studio apartment is characteriz...,The district in which you will be located is t...,https://a0.muscache.com/pictures/daaf2269-c947...,61225233,...,4.94,4.44,4.44,NaN,f,1,1,0,0,0.14
8000,750503110630802726,https://www.airbnb.com/rooms/750503110630802726,20250619031327,2025-06-19,city scrape,The Duomo Glam Apartment Gorgeous Baroque View,Enjoy the style of a charming apartment decora...,Piazza Santo Stefano is located in the heart o...,https://a0.muscache.com/pictures/miso/Hosting-...,158317747,...,5.00,4.97,4.88,IT015146C2NC8IAP3I,t,87,81,6,0,3.10
15000,1136714556931520755,https://www.airbnb.com/rooms/1136714556931520755,20250619031327,2025-06-19,city scrape,private room with bathroom,Welcome to our spacious loft in Milan's vibran...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,39495629,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN

In [10]:
df4= df.iloc[ [125] + [252] + list(range(300, 551)) + [700] + [1000] + list(range(1250, len(df))) , [9]+ [13]+ [17]+ [35]+ [39] +[71] ] 
df4

,host_id,host_location,host_acceptance_rate,bathrooms,amenities,review_scores_value
125,2332044,"London, United Kingdom",100%,1.5,"[""Washer"", ""Wifi"", ""Dedicated workspace"", ""Gar...",4.50
252,6753357,"Milan, Italy",97%,1.0,"[""Wifi"", ""Dishes and silverware"", ""Microwave"",...",4.78
300,1921860,"Milan, Italy",42%,2.0,"[""Freezer"", ""Dining table"", ""Body soap"", ""City...",4.57
301,3165404,"Milan, Italy",55%,NaN,"[""Wifi"", ""Freezer"", ""Dining table"", ""Dishes an...",4.69
302,12207778,"Milan, Italy",100%,1.0,"[""Wifi"", ""High chair"", ""Dining table"", ""Body s...",4.83
...,...,...,...,...,...,...
22535,701379726,"Milan, Italy",NaN,1.0,"[""Wifi"", ""Freezer"", ""Outdoor playground"", ""Dis...",NaN
22536,2574070,"Milan, Italy",100%,1.0,"[""Wifi"", ""Body soap"", ""Essentials"", ""Luggage d...",NaN
22537,303593576,"Milan, Italy",79%,1.0,"[""Wifi"", ""Freezer"", ""Solid.O conditioner"", ""Di...",NaN
22538,701442028,NaN,NaN,1.0,"[""Wifi"", ""Freezer"", ""Dining table"", ""Body soap...",NaN
22539,1761388,"Milan, Italy",88%,1.0,"[""Dryer"", ""High chair"", ""Wifi"", ""Freezer"", ""Di...",NaN

In [7]:
#Convertir archivo filtrado a CSV
columnas1.to_csv("Array(A).csv")

In [8]:
#Convertir archivo filtrado a CSV
df3.to_csv("Array(B).csv")

In [11]:
#Convertir archivo filtrado a CSV
df4.to_csv("Array(C).csv")